INSERT INTO cafe (id, name, type, description, has_delivery, delivery_price, delivery_price_from, minimal_order_price, delivery_time, delivery_work_start, delivery_work_end, site_url, phone_numbers, view_link, rank, work_start, work_end)
VALUES (1, 'Белладжио', 'Итальянская пиццерия', 'Пиццерия «Белладжио» — настоящая итальянская пиццерия премиум класса в центре Белгорода, с огромным выбором настоящей классической пиццы и вкуснейшими блюдами традиционной итальянской и японской кухни. Кроме того, в пиццерии «Белладжио» вы можете заказать пиццу, суши и роллы по телефону с доставкой на дом или в офис!
С нашей помощью вы можете заказать вкусную итальянскую пиццу и изысканную японскую кухню, не выходя из дома. «Белладжио» (Белгород) — уголок настоящей Италии ждет вас!
Отбросьте все сомнения, заказать традиционную пиццу и суши на дом в пиццерии «Белладжио» — просто и быстро! Мы доставим пиццу и суши в любую точку Белгорода максимально оперативно. Устройте себе настоящий итальянский или японский праздник, не выходя из дома!', 1, 500, 0, 1, null, '11:00:00', '00:00:00', 'http://bellagio31.ru/', '37-31-83', 'bellagio', 0, '11:00:00', '01:00:00');
INSERT INTO cafe (id, name, type, description, has_delivery, delivery_price, delivery_price_from, minimal_order_price, delivery_time, delivery_work_start, delivery_work_end, site_url, phone_numbers, view_link, rank, work_start, work_end) VALUES (2, 'Маленькая Италия', 'Пиццерия', 'Главное в итальянской кухне -гармония ,свежесть продуктов и хорошее настроение. Простая подача и незабываемый вкус –визитная карточка нашего кафе. На протяжении пяти лет кафе Маленькая Италия сохраняет вкусы и нравы итальянских семей. Мы угощаем гостей традиционными итальянскими блюдами: пицца, паста, лазанья. Те, кто ценит настоящую качественную еду - наши гости.

Кухня: Итальянская, Мексиканская, Японская', 1, 300, 0, 1, null, TO_TIMESTAMP('10:00:00', 'HH:MI:SS'), '22:00:00', 'http://кафебэст.рф/', '37-02-62', 'malenkaya-italiya', 0, '10:00:00', '23:00:00');
INSERT INTO cafe (id, name, type, description, has_delivery, delivery_price, delivery_price_from, minimal_order_price, delivery_time, delivery_work_start, delivery_work_end, site_url, phone_numbers, view_link, rank, work_start, work_end) VALUES (3, 'Потапыч', 'Кафе пиццерия', 'Сеть кафе-пиццерий «Потапыч» предлагает бесплатную доставку на дом и в офис.
 
Доставка осуществляется в течение 1-1.5 часов. В случае поступления большого количества заказов, а также сложной дорожной обстановки и плохих погодных условий время доставки может быть увеличено, о чем диспетчер сообщит дополнительно.

Заказ доставляется курьером в специальных коробках и контейнерах.

Блюда готовятся после принятия и подтверждения заказа диспетчером. Диспетчер свяжется с Вами в течение 5-10 минут после оформления интернет-заказа для подтверждения и окончательного расчета суммы заказа. Стоимость заказа калькулируется на основании действующих цен, стоимости упаковки и суммы скидки.', 1, 350, 1, 0, null, '11:00:00', '22:00:00', 'http://www.potapych-pizza.ru/', '37-47-01', 'potapych-pizza', 0, '10:00:00', '00:00:00');
INSERT INTO cafe (id, name, type, description, has_delivery, delivery_price, delivery_price_from, minimal_order_price, delivery_time, delivery_work_start, delivery_work_end, site_url, phone_numbers, view_link, rank, work_start, work_end) VALUES (6, '480 лет до нашей эры', 'Развлекательный центр', '', 1, 0, 0, 0, null, '08:00:00', '18:00:00', '', '35-38-87', '480-let-do-nashej-jery', 0, '00:00:00', '00:00:00');
INSERT INTO cafe (id, name, type, description, has_delivery, delivery_price, delivery_price_from, minimal_order_price, delivery_time, delivery_work_start, delivery_work_end, site_url, phone_numbers, view_link, rank, work_start, work_end) VALUES (10, 'Мастер пицца', 'Пиццерия', 'Мастер пицца это место, где вам всегда предложат самую вкусную пиццу, а также отменно приготовленные блюда японской и европейской кухни.
Ассортимент «Мастер Пиццы» достаточно широкий, чтобы каждый нашел что-то по своему вкусу. Чтобы довольным остались все вместе и каждый по отдельности. В меню представлено более 25 видов пиццы:  маргарита, тропикана, гавайская,  классическая, деревенская… – за каждым названием таятся вкусовые наслаждения. Так же предлагаем насладиться японской кухней. Всегда свежие продукты, искусство поваров и демократические цены. Рыба является основным продуктом японского меню. Мы готовим блюда в соответствии со сложившимися вековыми японскими традициями. Конечно, еда должна быть вкусной, здоровой и всегда свежей, но также блюда должны дарить эстетическое наслаждение своим видом. Для людей, которые привыкли к домашней кухне,  мы рекомендуем европейское меню, новинкой которого являются блюда, приготовленные на мангале (на древесных углях).', 1, 300, 0, 1, null, '11:00:00', '23:00:00', 'http://master-pizza31.ru/', '50-65-02', 'master-pizza', 0, '11:00:00', '23:00:00');
INSERT INTO cafe (id, name, type, description, has_delivery, delivery_price, delivery_price_from, minimal_order_price, delivery_time, delivery_work_start, delivery_work_end, site_url, phone_numbers, view_link, rank, work_start, work_end) VALUES (12, 'Буду Буду', 'Кафе пиццерия', '', 1, 300, 0, 1, null, '10:00:00', '23:00:00', 'http://кафебэст.рф/kafe-qbudu-buduq', '51-51-01', 'budu-budu', 0, '10:00:00', '23:00:00');
INSERT INTO cafe (id, name, type, description, has_delivery, delivery_price, delivery_price_from, minimal_order_price, delivery_time, delivery_work_start, delivery_work_end, site_url, phone_numbers, view_link, rank, work_start, work_end) VALUES (13, 'Сопрано', 'Кафе', 'Добро пожаловать в Сопрано – здесь всегда рады подарить вам частичку знойного солнца Италии!

Блюда в клубе европейские, преимущественно – итальянские. Внимание: вся еда в Сопрано готовится под заказ! Полуфабрикаты, микроволновка, «вторая свежесть» - в пиццерии гарантированно исключаются. Это краеугольный принцип Сопрано, так как здесь думают о здоровье посетителей и дорожат своей репутацией. В меню клуба есть эксклюзивные блюда, которых не отведаешь в других заведениях нашего города: например, фирменная пицца и паста. Услужливые официанты и бармены, в свою очередь, готовы выполнить любой ваш каприз. Не случайно проводить корпоративы, юбилеи, свадьбы, семейные праздники, просто обедать и ужинать в Сопрано уже стало традицией для многих белгородцев.', 1, 0, 0, 0, null, '09:00:00', '05:00:00', 'http://www.soprano-club.ru/', '8-903-886-88-98', 'soprano', 0, '09:00:00', '05:00:00');
INSERT INTO cafe (id, name, type, description, has_delivery, delivery_price, delivery_price_from, minimal_order_price, delivery_time, delivery_work_start, delivery_work_end, site_url, phone_numbers, view_link, rank, work_start, work_end) VALUES (14, 'Ташир', 'Пиццерия', 'В пиццериях «Ташир» сочетается высокое качество продукции и быстрота приготовления, это и стало визитной карточкой бренда. Вся пицца изготовлена по оригинальной технологии и рецептуре с использованием только свежих и качественных продуктов. Качество пиццы по достоинству оценили уже более 10 млн. посетителей. Ресторан быстрого обслуживания «Ташир Пицца» предлагает доставку еды, в то числе и доставка пиццы, на дом или в офис самого высокого качества. Вы уже сейчас можете сделать on-line заказ доставки пиццы и напитков в разделе «Доставка».

Итальянский буфет позволяет ценителям итальянской кухни отведать кулинарные шедевры самой изысканной кухни мира, а насыщенный аромат и превосходный вкус кофе подарят частичку тепла солнечной Италии.
Сегодня «Ташир пицца» это:
    1. Сочетание полноценной еды и быстрого обслуживания;
    2. Широкий ассортимент итальянских блюд;
    3. Доступные цены.
Наш посетитель - самый дорогой и желанный для нас гость. Обслуживать и быть всегда рядом с ним – большая честь для нашего сотрудника.', 1, 300, 0, 1, null, '09:00:00', '22:00:00', 'http://tashirpizza.ru/', '23-07-23', 'tashirpizza', 0, '09:00:00', '22:00:00');
INSERT INTO cafe (id, name, type, description, has_delivery, delivery_price, delivery_price_from, minimal_order_price, delivery_time, delivery_work_start, delivery_work_end, site_url, phone_numbers, view_link, rank, work_start, work_end) VALUES (15, 'Лайм', 'Пиццерия', '', 1, 300, 0, 1, null, '10:00:00', '23:00:00', 'http://кафебэст.рф/lajm-fresh-pitstsa', '32-66-03', 'lajm', 0, '10:00:00', '23:00:00');
INSERT INTO cafe (id, name, type, description, has_delivery, delivery_price, delivery_price_from, minimal_order_price, delivery_time, delivery_work_start, delivery_work_end, site_url, phone_numbers, view_link, rank, work_start, work_end) VALUES (18, 'Фабрика пиццы', 'Кафе пиццерия', 'Уютная атмосфера кафе-пиццерии "Фабрика пиццы" предлагает отдых, как всей семьей так и для дружной компании. Доступные цены. Качество и обслуживание на высшем уровне. Большой ассортимент пицц на любой вкус. Европейская кухня. Японская кухня. Широкий выбор пива и безалкогольных напитков. Просмотр спортивных событий. Банкетное обслуживание.

Доставка пиццы и всех блюд происходит сразу после приготовления.
Над Вашим заказом работают профессиональные повара и пиццайоло, на профессиональном оборудовании.
Доставка пиццы и всех блюд производится в специальных термосумках, позволяющих сохранить первозданную свежесть и полезные качества продуктов.
Наш шеф-повар постоянно работает над улучшением и доработкой меню, добавляя новые оригинальные блюда.', 1, 300, 1, 0, null, '10:00:00', '22:00:00', 'http://pizza-belgorod.ru/', '8-920-55-55-623', 'fabrika-pitstsy', 0, '10:00:00', '22:00:00');
INSERT INTO cafe (id, name, type, description, has_delivery, delivery_price, delivery_price_from, minimal_order_price, delivery_time, delivery_work_start, delivery_work_end, site_url, phone_numbers, view_link, rank, work_start, work_end) VALUES (21, 'Пиццемания', 'Пиццерия', '', 1, 350, 0, 1, null, '11:00:00', '22:00:00', 'http://pizzemania.ho4u-pizzu.ru/', '8-920-565-38-11', 'pitstsemaniya', 0, '11:00:00', '23:00:00');
INSERT INTO cafe (id, name, type, description, has_delivery, delivery_price, delivery_price_from, minimal_order_price, delivery_time, delivery_work_start, delivery_work_end, site_url, phone_numbers, view_link, rank, work_start, work_end) VALUES (28, 'Риц', 'Пиццерия', '', 1, 0, 0, 0, null, '10:00:00', '22:00:00', '', '52-85-75', 'rits', 0, '10:00:00', '23:00:00');
INSERT INTO cafe (id, name, type, description, has_delivery, delivery_price, delivery_price_from, minimal_order_price, delivery_time, delivery_work_start, delivery_work_end, site_url, phone_numbers, view_link, rank, work_start, work_end) VALUES (44, 'Ням-ням', 'Кафе пиццерия', '', 1, 300, 0, 1, null, '10:00:00', '23:00:00', '', '37-04-44', 'nyam-nyam', 0, '10:00:00', '23:00:00');
INSERT INTO cafe (id, name, type, description, has_delivery, delivery_price, delivery_price_from, minimal_order_price, delivery_time, delivery_work_start, delivery_work_end, site_url, phone_numbers, view_link, rank, work_start, work_end) VALUES (45, 'ДОДО пицца', 'Пиццерия', 'Доставим за 60 минут или пицца бесплатно.
Полная открытость. Закажи на сайте и наблюдай по <a href="https://dodopizza.ru/Belgorod/Webcam">вэб камере</a> за процессом приготовлением пиццы.
100% гарантия качества', 1, 325, 1, 0, null, '09:00:00', '00:00:00', 'https://dodopizza.ru/Belgorod', '8-800-333-00-60', 'dodopizza', 0, '08:50:00', '01:00:00');
INSERT INTO cafe (id, name, type, description, has_delivery, delivery_price, delivery_price_from, minimal_order_price, delivery_time, delivery_work_start, delivery_work_end, site_url, phone_numbers, view_link, rank, work_start, work_end) VALUES (46, 'Весёлый повар', 'Кафе пиццерия', '', 1, 300, 0, 1, null, '10:00:00', '23:00:00', 'http://кафебэст.рф/veselyj-povar', '37-40-03', 'vesyolyj-povar', 0, '10:00:00', '23:00:00');
INSERT INTO cafe (id, name, type, description, has_delivery, delivery_price, delivery_price_from, minimal_order_price, delivery_time, delivery_work_start, delivery_work_end, site_url, phone_numbers, view_link, rank, work_start, work_end) VALUES (47, 'Траттория', 'Кафе пиццерия', 'На пересечении улиц Н. Чумичова и бул.Народный есть уютное кафе с верандой. Это первое кафе в Белгороде с Мексиканской кухней. Хотите испробовать блюда знойной Мексики? Добро пожаловать! Наслаждайтесь «Фахитос» (огненная сковорода с мясом и овощами), Буррито ( мексиканская Тортилья с начинкой и специями),Мексиканскими салатами и чипсами «Начос»

Кухня: Мексиканская , Итальянская', 0, 0, 0, 0, null, null, null, 'http://кафебэст.рф/trattoriya', '27-02-04', 'trattoriya', 0, '10:00:00', '23:00:00');
INSERT INTO cafe (id, name, type, description, has_delivery, delivery_price, delivery_price_from, minimal_order_price, delivery_time, delivery_work_start, delivery_work_end, site_url, phone_numbers, view_link, rank, work_start, work_end) VALUES (48, 'Forno a Legna', 'Пиццерия', 'Интерьер выполнен в стиле старой Италии. Большая площадь заведения состоит из нескольких зон на 120 посадочных мест. Есть залы для курящих и не курящих. А также:
    1. дровяная печь
    2. приготовление пиццы с элементами акробатики на глазах у посетителей
    3. VIP-зал в охотничьем стиле
    4. летняя площадка
    5. банкомат в здании
    6. лаунж-музыка', 0, 0, 0, 0, null, null, null, '', '31-28-98', 'forno-a-legna', 0, '12:00:00', '00:00:00');
INSERT INTO cafe (id, name, type, description, has_delivery, delivery_price, delivery_price_from, minimal_order_price, delivery_time, delivery_work_start, delivery_work_end, site_url, phone_numbers, view_link, rank, work_start, work_end) VALUES (50, 'Cinema пицца', 'Пиццерия', 'Эта уютная пиццерия находится в здании кинотеатра "Русич".
Дизайн интерьера "Cinema пиццы" выдержан в стиле американского вестерна.
Здесь Вы можете весело провести время и отведать вкусной пиццы в ожидании любимого кинофильма.', 0, 0, 0, 0, null, null, null, '', '', 'cinema-pizza', 0, '11:00:00', '23:00:00');
INSERT INTO cafe (id, name, type, description, has_delivery, delivery_price, delivery_price_from, minimal_order_price, delivery_time, delivery_work_start, delivery_work_end, site_url, phone_numbers, view_link, rank, work_start, work_end) VALUES (51, 'KooDoo', 'Пиццерия', 'Для наших блюд мы используем только свежие ингредиенты. Мы работаем с лучшими российскими производителями по нашим стандартам.
Высочайшее качество является основной ценностью в KooDoo. И в то же время мы представляем быстрое обслуживание, веселье, страсть и приверженность семейным ценностям.', 1, 290, 1, 0, null, '10:00:00', '00:00:00', 'http://www.koodoofood.ru/', '8-800-550-33-50', 'koodoo', 0, '10:00:00', '23:00:00');
INSERT INTO cafe (id, name, type, description, has_delivery, delivery_price, delivery_price_from, minimal_order_price, delivery_time, delivery_work_start, delivery_work_end, site_url, phone_numbers, view_link, rank, work_start, work_end) VALUES (52, 'АмБар', 'Служба доставки', 'В своей работе мы используем самые передовые методы и технологии, позволяющие оказывать нам первоклассные услуги,по ценам, которые вам определенно понравятся. Если у вас появились вопросы, свяжитесь с нами. Мы с удовольствием поможем вам консультацией.
В ближайшем будущем порадуем Вас новыми услугами от АмБар.', 1, 450, 1, 0, null, '11:00:00', '23:00:00', 'http://ambar31.ru/', '77-06-05', 'ambar31', 0, '11:00:00', '23:00:00');
INSERT INTO cafe (id, name, type, description, has_delivery, delivery_price, delivery_price_from, minimal_order_price, delivery_time, delivery_work_start, delivery_work_end, site_url, phone_numbers, view_link, rank, work_start, work_end) VALUES (53, 'Жар-Пицца', 'Ресторан быстрого питания', 'Наши слагаемые успеха: удобное расположение ресторана + стабильность качества приготовления блюд + быстрый сервис + демократичная цена

Наши покупатели: любители вкусной и быстрой еды, предпочитающие компромисс между классическим фаст-фудом и блюдами, приготовленными для них вручную.

Наша команда: профессионалы своего дела и новички на рынке фаст-фуда, специалисты в своих областях и те, кто только начал делать первые шаги в бизнесе. Нас объединяет стремление учиться, развиваться и быть лучшими в своей отрасли.', 1, 350, 1, 0, null, '09:00:00', '21:00:00', 'http://zharpizza.ru/', '33-11-77', 'zharpizza', 0, '09:00:00', '21:00:00');
INSERT INTO cafe (id, name, type, description, has_delivery, delivery_price, delivery_price_from, minimal_order_price, delivery_time, delivery_work_start, delivery_work_end, site_url, phone_numbers, view_link, rank, work_start, work_end) VALUES (54, 'La Terrazza', 'Ресторан итальянской кухни', 'Семейный ресторан итальянской кухни «La Terrazza» — идеальное решение для всех, кто хочет отдохнуть, расслабиться и приятно провести время в семейном кругу, с друзьями и близкими людьми. Ценители настоящей, качественной еды — постоянные гости нашего ресторана! Джузеппе Малена шеф повар из Италии, ждет вас в гости в ресторане ла Терасса!!!', 1, 500, 0, 1, null, '10:00:00', '00:00:00', 'http://sushidom31.ru/la-terrazza/pizzas.html', '37-23-76', 'la-terrazza', 0, null, null);